kind: pipeline
type: docker
name: default

steps:
- name: nightly
  image: plugins/docker
  settings:
    repo: lflare/lemmy-subscriber-bot
    tags: nightly
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: release
  image: plugins/docker
  settings:
    repo: lflare/lemmy-subscriber-bot
    tags:
     - latest
     - ${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - tag
